version: '3.1'

services:
  movie-search-nginx-server:
    container_name: movie-search-nginx-server
    image: nginx
    restart: always
    volumes: 
      - .:/usr/share/nginx/html
    ports: 
      - 80:80